### ISSUE TITLE
Not started in the ForgeOptifine 1.7.10

### ISSUE THREAD

**Issue by ICaxapI** [LightWayUp/LegacyLauncher#2]
With the startin mc in the version 1.7.10 i'm get this message:

```
[17:25:36] [main/ERROR] [LaunchWrapper]: Failed to read cached_class_info.json
java.lang.IllegalArgumentException: Can not set java.util.concurrent.ConcurrentMap field net.minecraft.launchwrapper.CachedClassInfo.transformedClassNames to com.google.gson.internal.LinkedTreeMap
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:1.8.0_51]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:1.8.0_51]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[?:1.8.0_51]
	at java.lang.reflect.Field.set(Field.java:764) ~[?:1.8.0_51]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:95) ~[gson-2.2.4.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[gson-2.2.4.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[gson-2.2.4.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:741) ~[gson-2.2.4.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.initializeClassCacheSystem(LaunchClassLoader.java:145) [launchwrapper-2.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.<init>(LaunchClassLoader.java:70) [launchwrapper-2.0.jar:?]
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:31) [launchwrapper-2.0.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:23) [launchwrapper-2.0.jar:?]
```

**Comment by LightWayUp** [comment]
Sorry, but I can't seem to reproduce the issue 😕. This is tested with Forge for 1.7.10, OptiFine_1.7.10_HD_U_E7, Java 8 update 202, and [the binary release of launchwrapper compatible with Java 8](https://github.com/LightWayUp/LegacyLauncher/releases/download/v1.13-master/launchwrapper-1.13-master.jar).

![Forge OptiFine 1.7.10](https://i.imgur.com/OtA0CNt.png)

**Comment by ICaxapI** [comment]
> Java 8 update 202, and the binary release of launchwrapper compatible with Java 8

Will this not work on Java 12.0.2? I tried to run on java version 9+.

**Comment by LightWayUp** [comment]
> > Java 8 update 202, and the binary release of launchwrapper compatible with Java 8
> 
> Will this not work on Java 12.0.2? I tried to run on java version 9+.

Unfortunately only Forge 1.13+ works with Java 9+; this can't be solved by launchwrapper alone. Please see #1 for more information and references to the original discussion in Forge issues, thanks :slightly_smiling_face:.
